@startuml
'https://plantuml.com/sequence-diagram

'!theme amiga
skinparam sequenceMessageAlign center
'autonumber

actor "Nutzer"

Alice -> Bob: Authentication Request
Bob --> Alice: Authentication Response

activate "Nutzer"

"Nutzer" -> Alice: Anfrage

Alice -> Bob: Another authentication Request
Alice <-- Bob: another authentication Response

Alice --> "Nutzer": OK


@enduml